export const __esModule: boolean;
export const Plugin: typeof Plugin_1.Plugin;
export const Cache: typeof Cache_1.Cache;
export const VFS: typeof VFS_1.VFS;
export const Response: typeof ResponsePackage_1.ResponsePackage;
import Plugin_1 = require("./Plugin");
import Cache_1 = require("./Cache");
import VFS_1 = require("./VFS");
import ResponsePackage_1 = require("./ResponsePackage");
export { global as config, mode };
