name: Test

on:
  push:
  workflow_call:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: npm run test